## **Pandas_Data_Selection Notebook**

### **[], .loc, .iloc**

In this notebook we learn the 3 ways to select data from a DataFrame:

| Method | Selects by | Example |
|--------|-----------|---------|
| `df["col"]` | column name | `df["Age"]` |
| `df.loc[...]` | **labels** (names) | `df.loc[0:4, ["Name","Age"]]` |
| `df.iloc[...]` | **positions** (numbers) | `df.iloc[0:5, 0:3]` |

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\HP\Downloads\titanic_dataset.csv") # change the path if needed
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1306,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1307,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1308,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [3]:
# Coding
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

### **Selecting Columns**

### **Single Column** - returns a Series (1 column)

In [4]:
# Coding
df["Age"]

0       22.0
1       38.0
2       26.0
3       35.0
4       35.0
        ...
1304     NaN
1305    39.0
1306    38.5
1307     NaN
1308     NaN
Name: Age, Length: 1309, dtype: float64

### **List of Columns** - returns a DataFrame (note the double brackets!)

In [5]:
# Coding 
df[["Name", "Age", "PassengerId"]]

                                                   Name   Age  PassengerId
0                               Braund, Mr. Owen Harris  22.0            1
1     Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0            2
2                                Heikkinen, Miss. Laina  26.0            3
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0            4
4                              Allen, Mr. William Henry  35.0            5
...                                                 ...   ...          ...
1304                                 Spector, Mr. Woolf   NaN         1305
1305                       Oliva y Ocana, Dona. Fermina  39.0         1306
1306                       Saether, Mr. Simon Sivertsen  38.5         1307
1307                                Ware, Mr. Frederick   NaN         1308
1308                           Peter, Master. Michael J   NaN         1309

[1309 rows x 3 columns]

### **.loc** — Label-based Selection (VERY IMPORTANT)

Syntax: **df.loc[row_label, column_label]**

**.loc** uses the **index labels** and column **names**.

### Access Rows with labels: - loc includes the end - 5 rows!

In [16]:
# Coding 
df.loc[0:4]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

### Access Rows + specific columns together

In [7]:
# Coding 
df.loc[0:4,["Name", "Sex", "Age", "Embarked"]]

                                                Name     Sex   Age Embarked
0                            Braund, Mr. Owen Harris    male  22.0        S
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0        C
2                             Heikkinen, Miss. Laina  female  26.0        S
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0        S
4                           Allen, Mr. William Henry    male  35.0        S

### Access One selected Rows and selected Column

In [8]:
# Coding
df.loc[4, ["Name", "Age", "Embarked"]]

Name        Allen, Mr. William Henry
Age                             35.0
Embarked                           S
Name: 4, dtype: object

### Access all Rows and specific Columns - the ':' means everything

In [9]:
# Coding
df.loc[:, ["Name", "Pclass", "Survived", "Fare"]]

,Name,Pclass,Survived,Fare
0,"Braund, Mr. Owen Harris",3,0,7.2500
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,71.2833
2,"Heikkinen, Miss. Laina",3,1,7.9250
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,53.1000
4,"Allen, Mr. William Henry",3,0,8.0500
...,...,...,...,...
1304,"Spector, Mr. Woolf",3,0,8.0500
1305,"Oliva y Ocana, Dona. Fermina",1,1,108.9000
1306,"Saether, Mr. Simon Sivertsen",3,0,7.2500
1307,"Ware, Mr. Frederick",3,0,8.0500
1308,"Peter, Master. Michael J",3,0,22.3583

### **.iloc** — Position-based Selection

Syntax: **df.iloc[row_position, column_position]**

**.iloc** uses **integer positions** (0, 1, 2, ...) — like a list.

### Access First 5 Rows (iloc excludes the end - position 0,1,2,3,4)

In [10]:
# Coding
df.iloc[0:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Access Rows and Columns by position - first 5 rows and first 3 columns

In [11]:
# Coding 
df.iloc[0:5, 0:3]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

### **The Key Difference: **loc** vs **iloc**

| | `.loc[0:4]` | `.iloc[0:4]` |
|---|---|---|
| Selects by | label | position |
| End included? | **YES** (5 rows) | **NO** (4 rows) |

**Tip: GENERALLY USE `.loc` INSTEAD OF `.iloc`** — labels do not change when the data is
sorted or filtered, positions do.

### **set_index** — Now Labels and Positions Are DIFFERENT

Until now the index labels (0,1,2,...) happened to equal the positions, so `loc` and `iloc`
looked the same. Watch what happens when we make **PassengerId** the index.

In [12]:
# Coding
df.set_index("PassengerId", inplace = True)
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Now the index labels are 1 to 891 (Passenger Id), but positions are still 0 to 890

In [13]:
# Coding
df.loc[5]     # LABEL 1  -> passenger with PassengerId = 1  (the FIRST row)

Survived                           0
Pclass                             3
Name        Allen, Mr. William Henry
Sex                             male
Age                             35.0
SibSp                              0
Parch                              0
Ticket                        373450
Fare                            8.05
Cabin                            NaN
Embarked                           S
Name: 5, dtype: object

In [14]:
# Coding
df.iloc[4]      # POSITION 887 -> the 888th row (its PassengerId label is 888)
# note* position index and label index are different in number.

Survived                           0
Pclass                             3
Name        Allen, Mr. William Henry
Sex                             male
Age                             35.0
SibSp                              0
Parch                              0
Ticket                        373450
Fare                            8.05
Cabin                            NaN
Embarked                           S
Name: 5, dtype: object

### Same Passenger, two ways:

In [15]:
# Coding
print("By label   ->  df.loc[888]")
print("By position ->  df.iloc[887]")
df.loc[888].equals(df.iloc[887])

By label   ->  df.loc[888]
By position ->  df.iloc[887]

True

### **Summary**

- `df["col"]` -> one column (Series); `df[["c1","c2"]]` -> many columns (DataFrame)
- `.loc[rows, cols]` -> by **labels**, end **included**
- `.iloc[rows, cols]` -> by **positions**, end **excluded**
- After `set_index`, labels and positions become different — `.loc` follows the new index
- Prefer `.loc` in daily work