## **Pandas_Adding and Removing Notebook**

In [30]:
# Coding 
import pandas as pd
df= pd.DataFrame({
    "Name": ["James","Tony", "Lilly", "Patrick", "Robert", "Tom", "Angel"], 
    "Age": [23, 24, 28, 30, 20, 25, 29,], 
    "Sex": ["Male", "Male", "Female", "Male", "Male", "Male", "Female"], 
    "Survived": [1, 0, 0, 1, 1, 1, 0], 
    "Fare": [50, 100, 75, 60, 40, 120, 150]
})
df

      Name  Age     Sex  Survived  Fare
0    James   23    Male         1    50
1     Tony   24    Male         0   100
2    Lilly   28  Female         0    75
3  Patrick   30    Male         1    60
4   Robert   20    Male         1    40
5      Tom   25    Male         1   120
6    Angel   29  Female         0   150

### Add a new column using .loc: 
**Using .loc to add a column is permanently changed.**

In [31]:
#Coding
df.loc[:, "Embarked"]= "C"
df

      Name  Age     Sex  Survived  Fare Embarked
0    James   23    Male         1    50        C
1     Tony   24    Male         0   100        C
2    Lilly   28  Female         0    75        C
3  Patrick   30    Male         1    60        C
4   Robert   20    Male         1    40        C
5      Tom   25    Male         1   120        C
6    Angel   29  Female         0   150        C

### Adding a new column with multiple datas

In [32]:
# Coding
df.loc[:, "Transportation"]= ["Bus", "Train", "MotorCycle", "Car", "Bicycle", "Bus", "Train"]
df

      Name  Age     Sex  Survived  Fare Embarked Transportation
0    James   23    Male         1    50        C            Bus
1     Tony   24    Male         0   100        C          Train
2    Lilly   28  Female         0    75        C     MotorCycle
3  Patrick   30    Male         1    60        C            Car
4   Robert   20    Male         1    40        C        Bicycle
5      Tom   25    Male         1   120        C            Bus
6    Angel   29  Female         0   150        C          Train

### Adding a column based on Calculation

In [33]:
# Coding
df.loc[:, "Fare Raised"] = df["Fare"] * 1.50
df

      Name  Age     Sex  Survived  Fare Embarked Transportation  Fare Raised
0    James   23    Male         1    50        C            Bus         75.0
1     Tony   24    Male         0   100        C          Train        150.0
2    Lilly   28  Female         0    75        C     MotorCycle        112.5
3  Patrick   30    Male         1    60        C            Car         90.0
4   Robert   20    Male         1    40        C        Bicycle         60.0
5      Tom   25    Male         1   120        C            Bus        180.0
6    Angel   29  Female         0   150        C          Train        225.0

### Adding age on age column by 10 years

In [34]:
# Coding
df.loc[:, "Age Increase"] = df["Age"] +5
df

,Name,Age,Sex,Survived,Fare,Embarked,Transportation,Fare Raised,Age Increase
0,James,23,Male,1,50,C,Bus,75.0,28
1,Tony,24,Male,0,100,C,Train,150.0,29
2,Lilly,28,Female,0,75,C,MotorCycle,112.5,33
3,Patrick,30,Male,1,60,C,Car,90.0,35
4,Robert,20,Male,1,40,C,Bicycle,60.0,25
5,Tom,25,Male,1,120,C,Bus,180.0,30
6,Angel,29,Female,0,150,C,Train,225.0,34

### Adding a new column of age and decreasing the age by 2

In [35]:
# Coding 
df.loc[:, "Age Decrease"]= df["Age Increase"]-2
df

,Name,Age,Sex,Survived,Fare,Embarked,Transportation,Fare Raised,Age Increase,Age Decrease
0,James,23,Male,1,50,C,Bus,75.0,28,26
1,Tony,24,Male,0,100,C,Train,150.0,29,27
2,Lilly,28,Female,0,75,C,MotorCycle,112.5,33,31
3,Patrick,30,Male,1,60,C,Car,90.0,35,33
4,Robert,20,Male,1,40,C,Bicycle,60.0,25,23
5,Tom,25,Male,1,120,C,Bus,180.0,30,28
6,Angel,29,Female,0,150,C,Train,225.0,34,32

### Keeping only selected column by using loc

In [36]:
# Coding
a = df.loc[:, ["Name", "Age", "Sex", "Fare"]]
a

      Name  Age     Sex  Fare
0    James   23    Male    50
1     Tony   24    Male   100
2    Lilly   28  Female    75
3  Patrick   30    Male    60
4   Robert   20    Male    40
5      Tom   25    Male   120
6    Angel   29  Female   150

### Adding a new rows using a loc

In [37]:
# Coding
a.loc[7] = {"Name": "Mann", "Age": 26, "Sex": "Male"}
a

      Name  Age     Sex   Fare
0    James   23    Male   50.0
1     Tony   24    Male  100.0
2    Lilly   28  Female   75.0
3  Patrick   30    Male   60.0
4   Robert   20    Male   40.0
5      Tom   25    Male  120.0
6    Angel   29  Female  150.0
7     Mann   26    Male    NaN

### **For dictionary**:
Pandas will automatically fill missing columns with NaN.

### Adding a multiple rows at the same time using .loc

In [ ]:
# Coding 
a.loc[[8, 9, 10], :] = {
    "Name":["Thor", "Caspian", "Aslan"], 
    "Age": [22, 19, 20], 
    "Sex": ["Male", "Male", "Male"], 
    "Fare": [70]
}
a

In [ ]:
# Coding
a.loc[8]= {"Name": "Thor", "Age": 22, "Sex": "Male", "Fare": 70}
a.loc[9]= {"Name": "Caspian", "Age": 19, "Sex": "Male"}
a.loc[10]= {"Name": "Aslan", "Age": 20, "Sex": "Male"}
a

       Name  Age     Sex   Fare
0     James   23    Male   50.0
1      Tony   24    Male  100.0
2     Lilly   28  Female   75.0
3   Patrick   30    Male   60.0
4    Robert   20    Male   40.0
5       Tom   25    Male  120.0
6     Angel   29  Female  150.0
7      Mann   26    Male    NaN
8      Thor   22    Male   70.0
9   Caspian   19    Male    NaN
10    Aslan   20    Male    NaN

### Adding a multiple Columns at the same time using .loc

In [ ]:
# Coding 
#a.loc[:, ["Transportation", "ID", "Destination"]] = {
    #"Transportaton": ["Train", "Bus", "Car", "Bike", "Walking", "Train", "Bus", "Train"],
   # "Id": [102, 103, 104, 105, 106, 107, 108, 109], 
    #"Destination": ["Vienna", "Paris", "London", "Berlin", "Hampton", "Madrid", "Hamburg", "Dublin"]
}
#a

In [40]:
# Coding
a.loc[:, "Transportation"] = ["Train", "Bus", "Car", "Bike", "Walking", "Train", "Bus", "Train"]
a.loc[:, "ID"]= [ 102, 103, 104, 105, 106, 107, 108, 109 ]
a.loc[:, "Destination"] = ["Vienna", "Paris", "London", "Berlin", "Hampton", "Madrid", "Hamburg", "Dublin"]
a

      Name  Age     Sex   Fare Transportation   ID Destination
0    James   23    Male   50.0          Train  102      Vienna
1     Tony   24    Male  100.0            Bus  103       Paris
2    Lilly   28  Female   75.0            Car  104      London
3  Patrick   30    Male   60.0           Bike  105      Berlin
4   Robert   20    Male   40.0        Walking  106     Hampton
5      Tom   25    Male  120.0          Train  107      Madrid
6    Angel   29  Female  150.0            Bus  108     Hamburg
7     Mann   26    Male    NaN          Train  109      Dublin

### **Changing dataset**

In [42]:
import pandas as pd
b = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Clara'],
    'Age': [25, 30, 28],
    'Sex': ['female', 'male', 'female']
})
b

    Name  Age     Sex
0  Alice   25  female
1    Bob   30    male
2  Clara   28  female

### Change Bob's age and sex

In [43]:
# Coding
b.loc[b["Name"]== "Bob", ["Age", "Sex"]]= [31, "Male"]
b

    Name  Age     Sex
0  Alice   25  female
1    Bob   31    Male
2  Clara   28  female

### Changing name and age from a specific rows

In [44]:
# Coding
b.loc[b["Name"]== "Bob", ["Name", "Age"]]= ["Jennifer", 20]
b

       Name  Age     Sex
0     Alice   25  female
1  Jennifer   20    Male
2     Clara   28  female

### Changing Multiple Columns

In [45]:
# Coding 
b.loc[b["Name"]=="Jennifer", ["Age", "Sex", "Status"]]= [23, "Female", "Single"]
b

       Name  Age     Sex  Status
0     Alice   25  female     NaN
1  Jennifer   23  Female  Single
2     Clara   28  female     NaN

### **Using Set Index while adding and removing dataset**

In [47]:
# Coding 
b.set_index("Name", inplace = True)
b

          Age     Sex  Status
Name
Alice      25  female     NaN
Jennifer   23  Female  Single
Clara      28  female     NaN

### **Using iloc**

In [ ]:
# Coding
b.iloc[[0, 2], [0,3]]

    Name Status
0  Alice    NaN
2  Clara    NaN

### **Reseting the previous set index using .loc**

In [48]:
# Coding 
b.reset_index(inplace= True)
b

       Name  Age     Sex  Status
0     Alice   25  female     NaN
1  Jennifer   23  Female  Single
2     Clara   28  female     NaN

### **Using iloc**

In [51]:
# Coding 
b.iloc[1,[1,3]]

Age           23
Status    Single
Name: 1, dtype: object

### **Using loc**

In [54]:
# coding 
b.loc[[0,2], ["Name", "Sex"]]

    Name     Sex
0  Alice  female
2  Clara  female

### Examples of when you need **inplace=True** (including index operations)

| Operation | Default behavior | With **inplace=True** |
|-----------|----------------|------------------|
| **df.drop("x", axis=1)** | Returns a new DataFrame without column **"x"**; original **df** stays the same | Original **df** loses column **"x"** |
| **df.drop(0, axis=0)** | Returns a new DataFrame without row 0; original **df** unchanged | Original **df** loses row 0 |
| **df.sort_values("col")** | Returns a sorted copy; original **df** unchanged | Original **df** is sorted |
| **df.sort_index()** | Returns a copy sorted by index; original **df** unchanged | Original **df** is sorted by index |
| **df.fillna(0)** | Returns a copy with NaNs replaced | Original **df** modified |
| **df.rename(columns={"old":"new"})** | Returns a copy with renamed columns | Original **df** modified |
| **df.rename(index={0:"zero"})** | Returns a copy with renamed index | Original **df** index modified |
| **df.set_index("col")** | Returns a new DataFrame with **"col"** as index; original df unchanged | Original **df** now uses **"col"** as index |
| **df.reset_index()** | Returns a copy with index reset; original df unchanged | Original **df** index reset |