## **Pandas_Joins Notebook**

In pandas, we combine two DataFrames using **pd.merge()** — just like SQL joins.

Types of joins:
1. **Inner Join** — only matching rows
2. **Left Join** — all rows from left + matches from right
3. **Right Join** — all rows from right + matches from left
4. **Outer Join** — all rows from both

### **Joining two DataFrame**

In [14]:
import pandas as pd
students = pd.DataFrame({
    "Student ID": [101, 102, 103, 104, 105],
    "Name": ["Mann", "Patrick", "Jane", "Luna", "Peter"]
})
marks = pd.DataFrame({
    "Student ID": [101, 102, 103, 106, 107,],
    "Marks": [80, 86, 70, 75, 90]
})
students
marks

   Student ID  Marks
0         101     80
1         102     86
2         103     70
3         106     75
4         107     90

In [13]:
marks

   Student ID  Marks
0         101     80
1         102     86
2         103     70
3         104     75
4         105     90

### **Inner Join**
Keeps only rows where **student_id** exists in **both** tables.

Here: ids 1, 2, 3 (id 4 has no marks, id 5 has no student — both dropped).

In [15]:
# Coding 
inner = pd.merge(students, marks, on="Student ID", how="inner")
inner

   Student ID     Name  Marks
0         101     Mann     80
1         102  Patrick     86
2         103     Jane     70

### **Left Join**
Keeps **all rows from the left** table (**students**). Missing marks become **NaN**.

In [16]:
# Coding
left = pd.merge(students, marks, on= "Student ID", how= "left")
left

   Student ID     Name  Marks
0         101     Mann   80.0
1         102  Patrick   86.0
2         103     Jane   70.0
3         104     Luna    NaN
4         105    Peter    NaN

## **Right Join**
Keeps **all rows from the right** table (**marks**). Missing names become **NaN**.

In [17]:
# Coding 
right= pd.merge(students, marks, on = "Student ID", how = "right")
right

   Student ID     Name  Marks
0         101     Mann     80
1         102  Patrick     86
2         103     Jane     70
3         106      NaN     75
4         107      NaN     90

### **Outer Join**
Keeps **all rows from both** tables. Missing values become **NaN**.

In [18]:
# Coding 
outer = pd.merge(students, marks, on = "Student ID", how = "outer")
outer

   Student ID     Name  Marks
0         101     Mann   80.0
1         102  Patrick   86.0
2         103     Jane   70.0
3         104     Luna    NaN
4         105    Peter    NaN
5         106      NaN   75.0
6         107      NaN   90.0

### **Table Content**

| Join type | **how=** | Keeps |
|-----------|--------|-------|
| Inner | **'inner'** | Only matching rows |
| Left | **'left'** | All left rows |
| Right | **'right'** | All right rows |
| Outer | **'outer'** | All rows from both |