## **Pandas_Index_Set and Reset Notebook**

In [28]:
# Coding
import pandas as pd
df = pd.DataFrame({
    "Name": ["James", "Lilly", "Harry", "Peter", "Jack", "Ron", "Adin"], 
    "Age": [20, 24, 25, 26, 22, 21, 28], 
    "City": ["Paris", "Vienna", "Berlin", "Helsinki", "Tokyo", "London", "Oslo"], 
    "Occuption": ["Plumber", "IT", "Sales Person", "Manager", "Driver", "Designer", "Doctor"]
})
df

    Name  Age      City     Occuption
0  James   20     Paris       Plumber
1  Lilly   24    Vienna            IT
2  Harry   25    Berlin  Sales Person
3  Peter   26  Helsinki       Manager
4   Jack   22     Tokyo        Driver
5    Ron   21    London      Designer
6   Adin   28      Oslo        Doctor

### **Default Index**
By Default index, pandas always assigns a numeric index starting from 0

In [29]:
# Coding to check the index:
print(df.index)

RangeIndex(start=0, stop=7, step=1)

### **Set a Column as an index**

In [30]:
# Coding
df.set_index("Name")

       Age      City     Occuption
Name
James   20     Paris       Plumber
Lilly   24    Vienna            IT
Harry   25    Berlin  Sales Person
Peter   26  Helsinki       Manager
Jack    22     Tokyo        Driver
Ron     21    London      Designer
Adin    28      Oslo        Doctor

### **To set index permanently**

In [31]:
# Coding 
df.set_index("Name", inplace=True)
df

       Age      City     Occuption
Name
James   20     Paris       Plumber
Lilly   24    Vienna            IT
Harry   25    Berlin  Sales Person
Peter   26  Helsinki       Manager
Jack    22     Tokyo        Driver
Ron     21    London      Designer
Adin    28      Oslo        Doctor

### **To Reset Index**

In [32]:
# Coding
df.reset_index() 
# This is only temporary reset index.

    Name  Age      City     Occuption
0  James   20     Paris       Plumber
1  Lilly   24    Vienna            IT
2  Harry   25    Berlin  Sales Person
3  Peter   26  Helsinki       Manager
4   Jack   22     Tokyo        Driver
5    Ron   21    London      Designer
6   Adin   28      Oslo        Doctor

In [33]:
df

       Age      City     Occuption
Name
James   20     Paris       Plumber
Lilly   24    Vienna            IT
Harry   25    Berlin  Sales Person
Peter   26  Helsinki       Manager
Jack    22     Tokyo        Driver
Ron     21    London      Designer
Adin    28      Oslo        Doctor

### **To Reset index permanently**

In [34]:
# Coding
df.reset_index(inplace = True)
df

    Name  Age      City     Occuption
0  James   20     Paris       Plumber
1  Lilly   24    Vienna            IT
2  Harry   25    Berlin  Sales Person
3  Peter   26  Helsinki       Manager
4   Jack   22     Tokyo        Driver
5    Ron   21    London      Designer
6   Adin   28      Oslo        Doctor

### **What does inplace=True mean?**

- **inplace=True** means **modify the original DataFrame**
- No new DataFrame is created
- Changes happen **permanently**

#### Example:
Without inplace:
```python
new_df = df.set_index("Student_ID")

In [35]:
# Coding
import pandas as pd
df = pd.DataFrame({
    "Name": ["James", "Lilly", "Harry", "Peter", "Jack", "Ron", "Adin"], 
    "Age": [20, 24, 25, 26, 22, 21, 28], 
    "City": ["Paris", "Vienna", "Berlin", "Helsinki", "Tokyo", "London", "Oslo"], 
    "Occuption": ["Plumber", "IT", "Sales Person", "Manager", "Driver", "Designer", "Doctor"]
})
df

    Name  Age      City     Occuption
0  James   20     Paris       Plumber
1  Lilly   24    Vienna            IT
2  Harry   25    Berlin  Sales Person
3  Peter   26  Helsinki       Manager
4   Jack   22     Tokyo        Driver
5    Ron   21    London      Designer
6   Adin   28      Oslo        Doctor

In [37]:
# Coding
df.set_index("City")

           Name  Age     Occuption
City
Paris     James   20       Plumber
Vienna    Lilly   24            IT
Berlin    Harry   25  Sales Person
Helsinki  Peter   26       Manager
Tokyo      Jack   22        Driver
London      Ron   21      Designer
Oslo       Adin   28        Doctor

### Accessing data as Name - Jack and his age ansd palce where he live

In [43]:
# Coding 
df.iloc[4, [0, 1, 2]]

Name     Jack
Age        22
City    Tokyo
Name: 4, dtype: object

### Accessing first 3 rows data using iloc

In [46]:
# Coding 
df.iloc[0:3, 0:4]

    Name  Age    City     Occuption
0  James   20   Paris       Plumber
1  Lilly   24  Vienna            IT
2  Harry   25  Berlin  Sales Person

### Accessing last 3 rows data using iloc

In [47]:
# Coding
df.iloc[4:7, 0:4]

   Name  Age    City Occuption
4  Jack   22   Tokyo    Driver
5   Ron   21  London  Designer
6  Adin   28    Oslo    Doctor

### Keep Column Age as a default index using set_index

In [48]:
# Coding 
df.set_index("Age", inplace = True)
df

      Name      City     Occuption
Age
20   James     Paris       Plumber
24   Lilly    Vienna            IT
25   Harry    Berlin  Sales Person
26   Peter  Helsinki       Manager
22    Jack     Tokyo        Driver
21     Ron    London      Designer
28    Adin      Oslo        Doctor

### Reset the previous set_index 'Age' permanently

In [49]:
# Coding 
df.reset_index(inplace=True)
df

   Age   Name      City     Occuption
0   20  James     Paris       Plumber
1   24  Lilly    Vienna            IT
2   25  Harry    Berlin  Sales Person
3   26  Peter  Helsinki       Manager
4   22   Jack     Tokyo        Driver
5   21    Ron    London      Designer
6   28   Adin      Oslo        Doctor