## **Pandas_Sorting Notebook**

In [36]:
# Coding
import pandas as pd
df = pd.DataFrame({
    "Name": ["James", "Lilly", "Harry", "Peter", "Jack", "Ron", "Adin"], 
    "Age": [20, 24, 25, 26, 22, 21, 28], 
    "City": ["Paris", "Vienna", "Berlin", "Helsinki", "Tokyo", "London", "Oslo"], 
    "Marks": [68, 90, 80, 75, 78, 85, 60]
})
df

    Name  Age      City  Marks
0  James   20     Paris     68
1  Lilly   24    Vienna     90
2  Harry   25    Berlin     80
3  Peter   26  Helsinki     75
4   Jack   22     Tokyo     78
5    Ron   21    London     85
6   Adin   28      Oslo     60

### Use inplace = True to change data permannently

In [37]:
# Coding 
df.set_index("Name", inplace = True)
df

       Age      City  Marks
Name
James   20     Paris     68
Lilly   24    Vienna     90
Harry   25    Berlin     80
Peter   26  Helsinki     75
Jack    22     Tokyo     78
Ron     21    London     85
Adin    28      Oslo     60

### Sort the data by Age in ascending order

In [38]:
# Coding 
df.sort_values(by= "Age")

       Age      City  Marks
Name
James   20     Paris     68
Ron     21    London     85
Jack    22     Tokyo     78
Lilly   24    Vienna     90
Harry   25    Berlin     80
Peter   26  Helsinki     75
Adin    28      Oslo     60

### Sort the data by Age and Marks in Ascending order, but if the age is repeated, what will be the output?

In [39]:
# Coding
import pandas as pd
df = pd.DataFrame({
    "Name": ["James", "Lilly", "Harry", "Peter", "Jack", "Ron", "Adin"], 
    "Age": [20, 20, 25, 26, 20, 21, 28], 
    "City": ["Paris", "Vienna", "Berlin", "Helsinki", "Tokyo", "London", "Oslo"], 
    "Marks": [68, 90, 80, 75, 78, 85, 60]
})
df

    Name  Age      City  Marks
0  James   20     Paris     68
1  Lilly   20    Vienna     90
2  Harry   25    Berlin     80
3  Peter   26  Helsinki     75
4   Jack   20     Tokyo     78
5    Ron   21    London     85
6   Adin   28      Oslo     60

### Sort the data by multiple values such as Age and Marks

In [40]:
df.sort_values(by=["Age", "Marks"])

    Name  Age      City  Marks
0  James   20     Paris     68
4   Jack   20     Tokyo     78
1  Lilly   20    Vienna     90
5    Ron   21    London     85
2  Harry   25    Berlin     80
3  Peter   26  Helsinki     75
6   Adin   28      Oslo     60

### Here, pandas sort the data from Age not of the Marks, because pandas look for first in, first out.

### In case, the age contain same multiple data, pandas will sort by Marks in ascending order, but still pandas keep the Age in ascending order.

### Sort the data by Marks in descending order

In [41]:
# Coding 
df.sort_values(by="Marks", ascending = False)

    Name  Age      City  Marks
1  Lilly   20    Vienna     90
5    Ron   21    London     85
2  Harry   25    Berlin     80
4   Jack   20     Tokyo     78
3  Peter   26  Helsinki     75
0  James   20     Paris     68
6   Adin   28      Oslo     60

### **Sorting by Index or, Sort Index**

### Sorting by index in ascending order

In [44]:
# Coding 
df.sort_index()

   index   Name  Age      City  Marks
0      0  James   20     Paris     68
1      1  Lilly   20    Vienna     90
2      2  Harry   25    Berlin     80
3      3  Peter   26  Helsinki     75
4      4   Jack   20     Tokyo     78
5      5    Ron   21    London     85
6      6   Adin   28      Oslo     60

### Sorting by index in descending order

In [45]:
# Coding 
df.sort_index(ascending=False)

   index   Name  Age      City  Marks
6      6   Adin   28      Oslo     60
5      5    Ron   21    London     85
4      4   Jack   20     Tokyo     78
3      3  Peter   26  Helsinki     75
2      2  Harry   25    Berlin     80
1      1  Lilly   20    Vienna     90
0      0  James   20     Paris     68

### **Sorting data by Alphabetical order**

### Sorting by Names

In [46]:
# Coding 
df.sort_values(by= "Name")

   index   Name  Age      City  Marks
6      6   Adin   28      Oslo     60
2      2  Harry   25    Berlin     80
4      4   Jack   20     Tokyo     78
0      0  James   20     Paris     68
1      1  Lilly   20    Vienna     90
3      3  Peter   26  Helsinki     75
5      5    Ron   21    London     85

### Sorting by City

In [47]:
# Coding
df.sort_values("City")

   index   Name  Age      City  Marks
2      2  Harry   25    Berlin     80
3      3  Peter   26  Helsinki     75
5      5    Ron   21    London     85
6      6   Adin   28      Oslo     60
0      0  James   20     Paris     68
4      4   Jack   20     Tokyo     78
1      1  Lilly   20    Vienna     90

## 🧠 Quick Summary

| Task | Method |
|------|--------|
| Sort rows | **sort_values()** |
| Sort index | **sort_index()** |
| Descending order | **ascending=False** |
| Multiple columns | **by=[...]** |
| Save changes | **inplace=True** |
| Fix index | **reset_index(drop=True)** |