## **Pandas_Count_Clean_Heading Notebook**

This notebook focuses only on **counting data in Pandas**.

Using:

- **len()**
- **count()**
- **value_counts()**
- **nunique()**
- Counting with conditions
- **groupby().count()**
- **groupby().size()**
- **pd.crosstab()**
- Titanic counting examples

### **Import Pandas and Create Sample Data**

We will first use a small student dataset so the counting methods would be easy to understand.

In [1]:
import pandas as pd 
df = pd.DataFrame({
    
    "Name": ["Anita", "Bibek", "Chandra", "Dipesh", "Elina", "Farhan"],
    "Department": ["CSIT", "BCA", "CSIT", "BIM", "BCA", "CSIT"],
    "Age": [22, 21, 23, 24, 22, 25],
    "Score": [85, 72, 91, None, 68, 77],
    "City": ["Kathmandu", "Pokhara", "Kathmandu", "Butwal", "Pokhara", None]
})
df

      Name Department  Age  Score       City
0    Anita       CSIT   22   85.0  Kathmandu
1    Bibek        BCA   21   72.0    Pokhara
2  Chandra       CSIT   23   91.0  Kathmandu
3   Dipesh        BIM   24    NaN     Butwal
4    Elina        BCA   22   68.0    Pokhara
5   Farhan       CSIT   25   77.0       None

### **Count Total Rows with len()**

**len(df)** counts the total number of rows. It counts a row even if some values in that row are missing.

In [2]:
# Coding 
len(df)

6

### Count the total number of **Students** in the DataFrame

In [3]:
len(df["Name"])

6

### **Count Non-Missing Values with .count()**

**count()** counts only values that are not missing. If a column has **NaN**, those missing values are not counted.

In [4]:
# Coding 
df["Score"].count()

5

### Count the non-missing values in the cloumn - **"City"**

In [5]:
# Coding 
df["City"].count()

5

### **Count Non-Missing Values in Every Column**

**df.count()** returns the number of non-missing values for each column.

In [6]:
# Coding 
df.count()

Name          6
Department    6
Age           6
Score         5
City          5
dtype: int64

### **Count Values Row by Row**

Use **axis=1** to count non-missing values across each row.

In [7]:
# Coding 
df.count(axis=1)

0    5
1    5
2    5
3    4
4    5
5    4
dtype: int64

### **Count Frequency with value_counts()**

**value_counts()** tells us how many times each unique value appears.

In [8]:
# Coding 
df["Department"].value_counts()

CSIT    3
BCA     2
BIM     1
Name: Department, dtype: int64

### Count how many **Students** come from each **City**

In [9]:
# Coding 
df["City"].value_counts()

Kathmandu    2
Pokhara      2
Butwal       1
Name: City, dtype: int64

In [10]:
# Coding 
df.groupby("City")["Name"].count()

City
Butwal       1
Kathmandu    2
Pokhara      2
Name: Name, dtype: int64

### **Include Missing Values in value_counts()**

By default, **value_counts()** ignores missing values.

Use **dropna=False** to include them.

### Count **City** value including missing values

In [11]:
# Coding 
df["City"].value_counts(dropna= False)

Kathmandu    2
Pokhara      2
Butwal       1
None         1
Name: City, dtype: int64

### Count **Department** values and include missing values if any.

In [12]:
# Coding 
df["Department"].value_counts(dropna = False)

CSIT    3
BCA     2
BIM     1
Name: Department, dtype: int64

### **Count Unique Values with .nunique()**

**.nunique()** tells us how many different values exist.

### Count unique values from **Department**

In [13]:
# Coding 
df["Department"].nunique()

3

### Count how many unique **City** values are present.

In [14]:
# Coding 
df["City"].nunique()

3

### **Count Rows with a Condition**

A condition returns **True** or **False**.

In Pandas:

- **True** behaves like **1**
- **False** behaves like **0**

So **.sum()** can count how many rows satisfy the condition.

### Count **Students** whose Score is 80 or more

In [15]:
# Coding 
(df["Score"]>=80).sum()

# Note* .sum() will always count the value which are true, but .count() will always count the value which are both true and false.

2

In [16]:
# Coding 
df.loc[(df["Score"]> 80),:]

      Name Department  Age  Score       City
0    Anita       CSIT   22   85.0  Kathmandu
2  Chandra       CSIT   23   91.0  Kathmandu

### Count how many **Students** are from the **CSIT Department**.

In [17]:
# Coding 
(df["Department"]== "CSIT").sum()

3

In [18]:
# Coding 
df.loc[(df["Department"]== "CSIT"), :]

      Name Department  Age  Score       City
0    Anita       CSIT   22   85.0  Kathmandu
2  Chandra       CSIT   23   91.0  Kathmandu
5   Farhan       CSIT   25   77.0       None

### **Count with Multiple Conditions**

Use **&** when both conditions must be true.

### Count **CSIT students** whose Score is **80** or more

In [19]:
((df["Department"] == "CSIT") & (df["Score"]>= 80)).sum()

2

In [20]:
# Coding 
df.loc[(df["Department"]== "CSIT") & (df["Score"]>= 80), :]

      Name Department  Age  Score       City
0    Anita       CSIT   22   85.0  Kathmandu
2  Chandra       CSIT   23   91.0  Kathmandu

### Count **Students** who are from **Pokhara** and have **Age greater than 20**.

In [21]:
# Coding 
((df["City"]== "Pokhara") & (df["Age"]> 20)).sum()

2

In [22]:
# Coding 
df.loc[(df["City"]== "Pokhara") & (df["Age"]> 20), :]

    Name Department  Age  Score     City
1  Bibek        BCA   21   72.0  Pokhara
4  Elina        BCA   22   68.0  Pokhara

### **Count Groups with .groupby().count()**

**groupby().count()** counts non-missing values inside each group.

### Count available **Score** values inside each **Department**

In [23]:
# Coding 
df.groupby("Department")["Score"].count()

Department
BCA     2
BIM     0
CSIT    3
Name: Score, dtype: int64

### Count available **City** values inside each **Department**.

In [24]:
# Coding 
df.groupby("Department")['City'].count()

Department
BCA     2
BIM     1
CSIT    2
Name: City, dtype: int64

### **Count Total Rows per Group with .groupby().size()**

**size()** counts every row inside each group. This is different from **count()**, because **count()** ignores missing values.

### Count total students in each **Department**

In [25]:
# Coding 
df.groupby("Department")["Name"].size()

Department
BCA     2
BIM     1
CSIT    3
Name: Name, dtype: int64

### Count total rows for each **City** using groupby().size().

In [26]:
# Coding 
df.groupby("City").size()

City
Butwal       1
Kathmandu    2
Pokhara      2
dtype: int64

### **Analysis the Titanic Dataset**
Now apply the same counting methods to the Titanic dataset.

In [27]:
import pandas as pd 
a = pd.read_csv(r"C:\Users\HP\Downloads\titanic_dataset.csv")
a

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1306,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1307,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1308,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [28]:
# Coding 
a.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

### Q1. Count Total Titanic Passengers

In [29]:
# Coding 
len(a)

1309

### Q2. Count Male and Female Passengers

In [30]:
# Coding 
a["Sex"].value_counts()

male      843
female    466
Name: Sex, dtype: int64

### Q3. Count how many passengers are in each **Pclass**.

In [31]:
# Coding 
a.groupby("Pclass")["Name"].count()

Pclass
1    323
2    277
3    709
Name: Name, dtype: int64

In [32]:
# Coding 
a["Pclass"].value_counts()

3    709
1    323
2    277
Name: Pclass, dtype: int64

### Q4. Count Survivors and Deaths
In the Titanic dataset:

- **1** = Survived
- **0** = Died

### Q5. Count survived and died passengers

In [33]:
# Coding 
a["Survived"].value_counts()

0    815
1    494
Name: Survived, dtype: int64

### Q6. Count only passengers who died

In [34]:
# Coding 
(a["Survived"] == 0).sum()

815

### Q7. Count only passengers who survived

In [35]:
# Coding 
(a["Survived"]== 1).sum()

494

### **Count Missing Values**

Use **.isna().sum()** to count missing values in each column.

### Q8. Count missing values in every Titanic column

In [36]:
# Coding 
a.isna().sum()

PassengerId       0
Survived          0
Pclass            0
Name              0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
dtype: int64

### Q9. Count how many **Age** values are missing.

In [37]:
# Coding 
a["Age"].isna().sum()

263

### **Count Passengers by Group**

Use **groupby().size()** when you want the total number of rows in each group.

### Q10. Count passengers by **Sex**

In [38]:
# Coding
a["Sex"].value_counts()

male      843
female    466
Name: Sex, dtype: int64

In [39]:
# Coding 
a.groupby("Sex").size()

Sex
female    466
male      843
dtype: int64

### Q11. Count passengers by **Pclass** and **Sex**

In [40]:
# Coding 
a.groupby(["Pclass", "Sex"]).size()

Pclass  Sex
1       female    144
        male      179
2       female    106
        male      171
3       female    216
        male      493
dtype: int64

### **Counting Patterns to Remember**

**len(df)**  
→ total rows

**df["column"].count()**  
→ non-missing values

**df["column"].value_counts()**  
→ frequency of each value

**df["column"].nunique()**  
→ number of unique values

**(condition).sum()** 
→ count rows matching a condition

**df.groupby("column").size()**  
→ total rows in each group

**df.groupby("column")["value"].count()**  
→ non-missing values inside each group

**df.isna().sum()**  
→ count missing values

**pd.crosstab(col1, col2)**  
→ frequency table

### Q12. Count the total number of passengers in the Titanic dataset.

In [41]:
# Coding 
len(a)

1309

### Q13. Count how many male and female passengers are present.

In [42]:
# Coding 
a["Sex"].value_counts()

male      843
female    466
Name: Sex, dtype: int64

### Q14. Count how many passengers belong to each **Pclass**.

In [43]:
# Coding
a["Pclass"].value_counts()

3    709
1    323
2    277
Name: Pclass, dtype: int64

### Q15. Count how many passengers survived and how many died.

In [44]:
# Coding 
# Total Death of Passenger
(a["Survived"] == 0).sum()

815

In [45]:
# Coding
# Total Survive Passenger
(a["Survived"] == 1).sum()

494

### Q16. Count how many passengers have missing **Age** values.

In [46]:
# Coding 
a["Age"].isna().sum()

263

### Q17. Count how many passengers have missing **Cabin** values.

In [47]:
# Coding 
a["Cabin"].isna().sum()

1014

### Q18. Count how many passengers are male and survived.

In [48]:
# Coding 
((a["Sex"]== "male") & (a["Survived"]== 1)).sum()

109

### Q19. Count the total number of passengers for each **Embarked** value.

In [49]:
# Coding 
a["Embarked"].value_counts()

S    914
C    270
Q    123
Name: Embarked, dtype: int64

In [50]:
# Coding 
a.groupby("Embarked").size()

Embarked
C    270
Q    123
S    914
dtype: int64

### Q20. Count passengers for every **Pclass** and **Sex** combination using **groupby().size()**.

In [51]:
# Coding 
a.groupby(["Pclass", "Sex"]).size()

Pclass  Sex
1       female    144
        male      179
2       female    106
        male      171
3       female    216
        male      493
dtype: int64

### Q21. Create a cross-tabulation showing **Sex** against **Survived**.

In [52]:
# Coding 
#a = pd.crosstab(a["Sex"], df["Survived"])
#print(a)

In [53]:
# Coding 
a.groupby(["Sex", "Survived"]).size()

Sex     Survived
female  0            81
        1           385
male    0           734
        1           109
dtype: int64