# **Pandas Notebook**

### **Pandas Series (1-D Data)**
A Series is a one-dimensional labeled array.

Think of it like:

A single column of a table

Or a vector with labels (index)s**: 

It extract and look to the data horizontally (Rows), and vertically (column) of one dimension.

In [1]:
# Syntax: 
import pandas as pd 
df = pd.Series([10, 20, 30, 40])
df

0    10
1    20
2    30
3    40
dtype: int64

### **Series with Custom Index**:

In [2]:
# Example: 
marks = pd.Series([85, 90, 88], index=["James", "Star", "Ron"])
marks

James    85
Star     90
Ron      88
dtype: int64

In [3]:
# For Indexing in Series: 
marks [1]

90

### **Pandas DataFrame (2-D Data)**
A DataFrame is a table (rows + columns), like Excel or SQL table

In [4]:
#Example practice:
import pandas as pd
df = pd.DataFrame({
    "Name": ["James", "Peter", "lilly", "Parker", "Mann", "Tony"],
    "Position": ["IT", "Marketing", "Janitor", "Manager", "Director", "Sales Person"], 
    "Salary": [5000, 4000, 3000, 2000, 2500, 3000 ]
})
df

     Name      Position  Salary
0   James            IT    5000
1   Peter     Marketing    4000
2   lilly       Janitor    3000
3  Parker       Manager    2000
4    Mann      Director    2500
5    Tony  Sales Person    3000

### **Select Columns** (very important)
#### **Single column → Series**
#### **Multiple columns → DataFrame**

### For Single Column extraction:

In [5]:
#Example practice:
import pandas as pd
df = pd.DataFrame({
    "Name": ["James", "Peter", "lilly", "Parker", "Mann", "Tony"],
    "Position": ["IT", "Marketing", "Janitor", "Manager", "Director", "Sales Person"], 
    "Salary": [5000, 4000, 3000, 2000, 2500, 3000 ]
})
df
df["Name"]

0     James
1     Peter
2     lilly
3    Parker
4      Mann
5      Tony
Name: Name, dtype: object

### For Multiple Column Extraction:

In [6]:
# Example: 
import pandas as pd
df = pd.DataFrame({
    "Name": ["Mann", "Peter", "Tony", "James", "Jude", "Lilly"], 
    "Age": [24, 25, 20, 23, 27, 28], 
    "Department": ["IT", "Sales", "Manager", "Director", "Marketing", "Consuler"], 
    "Salary": [2000, 3000, 2500, 1500, 2000, 2300]
})
df
df[["Name", "Salary", "Age"]]

    Name  Salary  Age
0   Mann    2000   24
1  Peter    3000   25
2   Tony    2500   20
3  James    1500   23
4   Jude    2000   27
5  Lilly    2300   28

### **Finding the first 2 and last 2 from the dataframe**:

### **Head**

In [7]:
# Example: Head
import pandas as pd
df = pd.DataFrame({
    "Name": ["Mann", "Peter", "Tony", "James", "Jude", "Lilly"], 
    "Age": [24, 25, 20, 23, 27, 28], 
    "Department": ["IT", "Sales", "Manager", "Director", "Marketing", "Consuler"], 
    "Salary": [2000, 3000, 2500, 1500, 2000, 2300]
})
df
df.head(2)

    Name  Age Department  Salary
0   Mann   24         IT    2000
1  Peter   25      Sales    3000

### **Tail**

In [8]:
# Example: Tail
import pandas as pd
df = pd.DataFrame({
    "Name": ["Mann", "Peter", "Tony", "James", "Jude", "Lilly"], 
    "Age": [24, 25, 20, 23, 27, 28], 
    "Department": ["IT", "Sales", "Manager", "Director", "Marketing", "Consuler"], 
    "Salary": [2000, 3000, 2500, 1500, 2000, 2300]
})
df
df.tail(2)
#df.shape

    Name  Age Department  Salary
4   Jude   27  Marketing    2000
5  Lilly   28   Consuler    2300

### **Shape**

In [9]:
# Example: Shape
import pandas as pd
df = pd.DataFrame({
    "Name": ["Mann", "Peter", "Tony", "James", "Jude", "Lilly"], 
    "Age": [24, 25, 20, 23, 27, 28], 
    "Department": ["IT", "Sales", "Manager", "Director", "Marketing", "Consuler"], 
    "Salary": [2000, 3000, 2500, 1500, 2000, 2300]
})
df
df.shape

(6, 4)

### **Sample**

In [10]:
# Example: Sample
import pandas as pd
df = pd.DataFrame({
    "Name": ["Mann", "Peter", "Tony", "James", "Jude", "Lilly"], 
    "Age": [24, 25, 20, 23, 27, 28], 
    "Department": ["IT", "Sales", "Manager", "Director", "Marketing", "Consuler"], 
    "Salary": [2000, 3000, 2500, 1500, 2000, 2300]
})
df
df.sample()

    Name  Age Department  Salary
3  James   23   Director    1500

### **To Save and Generate data into Local System**

In [11]:
df.to_csv('data.csv', index = False) 
# Index = False avoids adding row numbers

### **Apply all the analysis such as info, shape, describe and other things in data, and find the first and last 10 data**:

In [12]:
# Coding
import pandas as pd
a = pd.DataFrame({
    "Name":
        ["Aarav","Bibek","Chirag","Dipesh","Elina","Firoz","Gaurav","Himanshu","Ishan","Jasmine","Kiran","Laxmi",
        "Manish","Nisha","Om","Prabin","Riya","Sagar","Sanjay","Tanya","Utsav","Varsha","Wasim","Xavier","Yash",
        "Zoya","Anisha","Bikash","Chetan","Deepa"],
    "Age":
        [25, 28, 31, 27, 35, 30, 26, 33, 29, 32, 25, 34, 28, 31, 27, 30, 35, 26, 33, 29, 32, 25, 34, 30, 28, 27, 31, 35, 26, 33], 
    "Department":
        ["Human Resources","Finance","Accounting","Marketing","Sales", "Information Technology", "Customer Service",
        "Operations", "Production", "Research and Development", "Procurement", "Purchasing", "Legal", "Administration", "Quality Assurance",
        "Supply Chain", "Logistics", "Warehouse", "Engineering", "Product Management","Public Relations", "Information Security",
        "Maintenance", "Health and Safety", "Training and Development","Business Development", "Risk Management", "Compliance",
        "Internal Audit", "Data Analytics"],
    "Salary": 
        [10245,13789,15432,16875,19346,21458,23791,25634,27856,30129,32467,34581,36742,38915,41273,43596,45821,47638,50317,52649,54872,57136,59428,
        61375,63841,65729,68154,70436,72581,74963]
})
a

        Name  Age                Department  Salary
0      Aarav   25           Human Resources   10245
1      Bibek   28                   Finance   13789
2     Chirag   31                Accounting   15432
3     Dipesh   27                 Marketing   16875
4      Elina   35                     Sales   19346
5      Firoz   30    Information Technology   21458
6     Gaurav   26          Customer Service   23791
7   Himanshu   33                Operations   25634
8      Ishan   29                Production   27856
9    Jasmine   32  Research and Development   30129
10     Kiran   25               Procurement   32467
11     Laxmi   34                Purchasing   34581
12    Manish   28                     Legal   36742
13     Nisha   31            Administration   38915
14        Om   27         Quality Assurance   41273
15    Prabin   30              Supply Chain   43596
16      Riya   35                 Logistics   45821
17     Sagar   26                 Warehouse   47638
18    Sanjay   33               Engineering   50317
19     Tanya   29        Product Management   52649
20     Utsav   32          Public Relations   54872
21    Varsha   25      Information Security   57136
22     Wasim   34               Maintenance   59428
23    Xavier   30         Health and Safety   61375
24      Yash   28  Training and Development   63841
25      Zoya   27      Business Development   65729
26    Anisha   31           Risk Management   68154
27    Bikash   35                Compliance   70436
28    Chetan   26            Internal Audit   72581
29     Deepa   33            Data Analytics   74963

### **Head -10**

In [13]:
# Coding
a.head(10)

       Name  Age                Department  Salary
0     Aarav   25           Human Resources   10245
1     Bibek   28                   Finance   13789
2    Chirag   31                Accounting   15432
3    Dipesh   27                 Marketing   16875
4     Elina   35                     Sales   19346
5     Firoz   30    Information Technology   21458
6    Gaurav   26          Customer Service   23791
7  Himanshu   33                Operations   25634
8     Ishan   29                Production   27856
9   Jasmine   32  Research and Development   30129

### **Tail -10**

In [14]:
# Coding
a.tail(10)

      Name  Age                Department  Salary
20   Utsav   32          Public Relations   54872
21  Varsha   25      Information Security   57136
22   Wasim   34               Maintenance   59428
23  Xavier   30         Health and Safety   61375
24    Yash   28  Training and Development   63841
25    Zoya   27      Business Development   65729
26  Anisha   31           Risk Management   68154
27  Bikash   35                Compliance   70436
28  Chetan   26            Internal Audit   72581
29   Deepa   33            Data Analytics   74963

### **Shape**

In [15]:
# Coding
a.shape

(30, 4)

### **Describe**

In [16]:
# Coding
a.describe()

             Age        Salary
count  30.000000     30.000000
mean   29.833333  42568.966667
std     3.259822  19520.757925
min    25.000000  10245.000000
25%    27.000000  26189.500000
50%    30.000000  42434.500000
75%    32.750000  58855.000000
max    35.000000  74963.000000

### **Info**

In [17]:
# Coding
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        30 non-null     object
 1   Age         30 non-null     int64
 2   Department  30 non-null     object
 3   Salary      30 non-null     int64
dtypes: int64(2), object(2)
memory usage: 1.1+ KB

### **Pandas loc and iloc**:

In [18]:
# Example:
import pandas as pd
data = {
    "Name": ["James", "Mann", "Tony", "Peter"], 
    "Id": [101, 102, 103, 104], 
    "Marks": [50, 60, 70, 85]
}
df = pd.DataFrame(data)
df

    Name   Id  Marks
0  James  101     50
1   Mann  102     60
2   Tony  103     70
3  Peter  104     85

### **loc - Label Base Indexing**:

- **loc** is used to access data using **labels**
- Labels can be:
  - Index names /row label
  - Column names
- **Both start and end values are included**

In [19]:
# Example; 
df.set_index("Id", inplace=True)
df

      Name  Marks
Id
101  James     50
102   Mann     60
103   Tony     70
104  Peter     85

**loc = access data using label index name value, not index position**

### Accessing Single or specific rows using loc

In [20]:
# Example: 
df.loc[103,"Name"]

'Tony'

### Accessing Double and multiple rows using loc

In [21]:
# Exmaple:
df.loc[[103, 104]]   
# Access multiple rows

      Name  Marks
Id
103   Tony     70
104  Peter     85

### Accessing Multiple rows and column using loc

In [22]:
# Example:
df.loc[101:103,["Name", "Marks"]]

      Name  Marks
Id
101  James     50
102   Mann     60
103   Tony     70

### **iloc - Integer Position based Indexing**:

- **iloc** uses **integer positions**
- Index starts from **0**
- **End value is excluded**
- Similar to Python list slicing

In [23]:
# Example:
import pandas as pd
data = {
    "Name": ["James", "Lilly", "Thor", "Peter"], 
    "Id": [101, 102, 103, 104], 
    "Marks": [50, 60, 70, 85]
}
df = pd.DataFrame(data)
df

    Name   Id  Marks
0  James  101     50
1  Lilly  102     60
2   Thor  103     70
3  Peter  104     85

In [24]:
# Example:
df.set_index("Marks") 
df

    Name   Id  Marks
0  James  101     50
1  Lilly  102     60
2   Thor  103     70
3  Peter  104     85

### Access multiple rows using iloc

In [25]:
# Exmaple: 
df.iloc[[0,2]]

    Name   Id  Marks
0  James  101     50
2   Thor  103     70

### Access specific rows and column using iloc

In [26]:
# Example: 
df.iloc[2,1]

103

### Access Range of Rows and Column using iloc

In [27]:
# Example: 
df.iloc[0:3, 0:2]

    Name   Id
0  James  101
1  Lilly  102
2   Thor  103

### **Comparison Table**

| Feature | loc | iloc |
|------|-----|------|
| Type | Label-based | Integer position-based |
| Uses | Index & column names | Row & column numbers |
| Range | End included | End excluded |
| Similar to | Dictionary | Python list |
| Example | df.loc[101] | df.iloc[0] |

### **Common Mistakes**

❌ Using labels in **iloc**
```python
df.iloc[101]   # Error


### 📌 **10. When to Use What? (Markdown Cell)**

```markdown
### When to Use **loc**
- When index has meaningful labels (ID, Name, Date)
- When readability is important

### When to Use **iloc**
- When working with positions
- When index values are unknown
- For fast slicing like arrays