## **Pandas_Data_Cleaning Notebook**

### Data Cleaning with Pandas: Titanic Dataset

In this notebook we clean the Titanic dataset step by step:

**Workflow:**
1. Load and inspect the data
2. Warm up: **loc** and **iloc**
3. Handle missing values
4. Remove duplicates
5. Fix data types
6. Handle outliers
7. Clean text and categories
8. Verify and save

**Golden rule:** Inspect before cleaning, verify after cleaning.

### **Step 0: Load the Data**

If you have **titanic.csv** in the same folder, use that. Otherwise the second line loads it from the internet.

In [3]:
# Coding 
import pandas as pd
df = pd.read_csv(r"C:\Users\HP\Downloads\titanic_dataset.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1306,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1307,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1308,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [4]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

### **Step 1: Inspect the Data**

Never clean blindly. First understand what you have.

In [5]:
# Coding 
df.shape 

# Note* df.shape gives you the inforamtion about the total rows and columns in the dataset.

(1309, 12)

In [6]:
# Coding 
df.info()

# Note* types + non-null counts (most useful first check)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     1309 non-null   int64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   object
 4   Sex          1309 non-null   object
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    object
 11  Embarked     1307 non-null   object
dtypes: float64(2), int64(5), object(5)
memory usage: 122.8+ KB

In [7]:
# Coding
df.describe()

# Note* Statistics of numeric columns

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,1309.000000,1309.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000
mean,655.000000,0.377387,2.294882,29.881138,0.498854,0.385027,33.295479
std,378.020061,0.484918,0.837836,14.413493,1.041658,0.865560,51.758668
min,1.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,328.000000,0.000000,2.000000,21.000000,0.000000,0.000000,7.895800
50%,655.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,982.000000,1.000000,3.000000,39.000000,1.000000,0.000000,31.275000
max,1309.000000,1.000000,3.000000,80.000000,8.000000,9.000000,512.329200

**What we can already see from **info()**:**
- **Ag** has missing values (count is less than total rows)
- **Cabin** is mostly missing
- **Embarked** is missing in 2 rows

### **Step 2: Warm Up with** **loc** and **iloc**

**loc** selects by **name (label)**. **iloc** selects by **position number**.

Pattern: **df.loc[rows, columns]**

In [8]:
# Coding 
df.loc[0, "Age"]

# Note* one cell: row 0, column "Age"

22.0

In [9]:
# Coding 
df.loc[0:4, ["Name", "Age", "Fare"]]

# Note* some rows, some columns (loc includes the end label 4)

                                                Name   Age     Fare
0                            Braund, Mr. Owen Harris  22.0   7.2500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                             Heikkinen, Miss. Laina  26.0   7.9250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                           Allen, Mr. William Henry  35.0   8.0500

In [10]:
# Coding 
df.iloc[0:5, [3,5,9]]

# Note* iloc: same idea but with position numbers (stops BEFORE 5)

                                                Name   Age     Fare
0                            Braund, Mr. Owen Harris  22.0   7.2500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                             Heikkinen, Miss. Laina  26.0   7.9250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                           Allen, Mr. William Henry  35.0   8.0500

### **loc** with conditions (filtering)

This is the most important skill in this notebook.

### Passenger older than 60

In [11]:
# Coding 
df.loc[df["Age"]> 60, ["Name", "Age", "Survived"]]

                                                   Name   Age  Survived
33                                Wheadon, Mr. Edward H  66.0         0
54                       Ostby, Mr. Engelhart Cornelius  65.0         0
96                            Goldschmidt, Mr. George B  71.0         0
116                                Connors, Mr. Patrick  70.5         0
170                           Van der hoef, Mr. Wyckoff  61.0         0
252                           Stead, Mr. William Thomas  62.0         0
275                   Andrews, Miss. Kornelia Theodosia  63.0         1
280                                    Duane, Mr. Frank  65.0         0
326                           Nysveen, Mr. Johan Hansen  61.0         0
438                                   Fortune, Mr. Mark  64.0         0
456                           Millet, Mr. Francis Davis  65.0         0
483                              Turkula, Mrs. (Hedwig)  63.0         1
493                             Artagaveytia, Mr. Ramon  71.0         0
545                        Nicholson, Mr. Arthur Ernest  64.0         0
555                                  Wright, Mr. George  62.0         0
570                                  Harris, Mr. George  62.0         1
625                               Sutton, Mr. Frederick  61.0         0
630                Barkworth, Mr. Algernon Henry Wilson  80.0         1
672                         Mitchell, Mr. Henry Michael  70.0         0
745                        Crosby, Capt. Edward Gifford  70.0         0
829           Stone, Mrs. George Nelson (Martha Evelyn)  62.0         1
851                                 Svensson, Mr. Johan  74.0         0
893                           Myles, Mr. Thomas Francis  62.0         0
904                                Howard, Mr. Benjamin  63.0         0
972                                  Straus, Mr. Isidor  67.0         0
987   Cavendish, Mrs. Tyrell William (Julia Florence...  76.0         1
1005             Straus, Mrs. Isidor (Rosalie Ida Blun)  63.0         1
1033                         Ryerson, Mr. Arthur Larned  61.0         0
1043                                 Storey, Mr. Thomas  60.5         0
1070  Compton, Mrs. Alexander Taylor (Mary Eliza Ing...  64.0         1
1084                                  Lingane, Mr. John  61.0         0
1127                           Warren, Mr. Frank Manley  64.0         0
1196  Crosby, Mrs. Edward Gifford (Catherine Elizabe...  64.0         1

### Females in first class **(use & for AND, | for OR, brackets around each condition)**

In [12]:
# Coding 
df.loc[(df["Sex"]== "female") & (df["Pclass"]== 1), :].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C

### **loc** for updating values

**loc** is the **safe** way to change values. Select with a condition, then write into those rows.

### Label Children and Adult

In [13]:
# Coding 
df.loc[df["Age"]< 16, "Group"] = "Child"
df.loc[df["Age"]>= 16, "Group"] = "Adult"
#df[["Name", "Age", "Group"]].head(10)
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,NaN
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Adult
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,Child
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,Adult
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,Child

Note*: rows where **Age** is missing got neither label, so their **Group** is **NaN**. We will fix **Age** next, then you can rerun the labeling.

We used **Group** only for practice. Let us drop it before cleaning.

### To delete column from the dataset:

In [14]:
# Coding 
df = df.drop(columns= ["Group"])
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1306,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1307,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1308,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

### **Step 3: Missing Values**

### ***Finding missing values first***

In [15]:
# Coding 
df.isnull().sum()

PassengerId       0
Survived          0
Pclass            0
Name              0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
dtype: int64

### Convert all the null data in to percentage form so that we can decide what to do or, to fill the null value or just dropped it.

In [16]:
# Coding 
(df.isnull().mean()* 100).round(1)

PassengerId     0.0
Survived        0.0
Pclass          0.0
Name            0.0
Sex             0.0
Age            20.1
SibSp           0.0
Parch           0.0
Ticket          0.0
Fare            0.1
Cabin          77.5
Embarked        0.2
dtype: float64

### Look at some rows where Age is missing, using .loc

In [17]:
# Coding 
df.loc[df["Age"].isnull(), ["Name", "Age", "Pclass"]]

                                 Name  Age  Pclass
5                    Moran, Mr. James  NaN       3
17       Williams, Mr. Charles Eugene  NaN       2
19            Masselmani, Mrs. Fatima  NaN       3
26            Emir, Mr. Farred Chehab  NaN       3
28      O'Dwyer, Miss. Ellen "Nellie"  NaN       3
...                               ...  ...     ...
1299  Riordan, Miss. Johanna Hannah""  NaN       3
1301           Naughton, Miss. Hannah  NaN       3
1304               Spector, Mr. Woolf  NaN       3
1307              Ware, Mr. Frederick  NaN       3
1308         Peter, Master. Michael J  NaN       3

[263 rows x 3 columns]

### ***3.2 Decide and act***

| Column | Missing | Decision |
|--------|---------|----------|
| Cabin | ~77% | **Drop the column** (too empty to be useful) |
| Embarked | 2 rows | **Fill with mode** (most common port) |
| Age | ~20% | **Fill with median** (too important to drop) |

### To drop Cabin column

In [18]:
# Coding
df = df.drop(columns=["Cabin"])
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,S
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C
1306,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,S
1307,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,S
1308,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,C

### Fill Embarked column with the mode (most common value)

In [19]:
# Coding 
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

In [20]:
# Coding 
df.loc[df["Embarked"].isna(), "Embarked"] = df['Embarked'].mode()[0]

### **Calculate the Median**

In [21]:
# Coding 
median_age= df["Age"].median()
print("Median Age:", median_age)

Median Age: 28.0

In [22]:
# Coding 
df.loc[df["Age"].isna(), "Age"] = median_age

### **Verifying the Missing values**:

In [23]:
# Coding 
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           1
Embarked       0
dtype: int64

### **Note*** 
**Why median and not mean?** The mean gets pulled by outliers (a few very old passengers), the median does not.

### **Step 4: Duplicates**

The real Titanic data has no duplicates, so let us **create some on purpose** to practice.

### **Checking Duplicates in the dataset**

In [24]:
# Coding 
df.duplicated().sum()

0

### **Add the first 3 rows again as fake duplicates**

In [25]:
# Coding 
df = pd.concat([df, df.iloc[0:3]], ignore_index=True)

print("Rows now:", len(df))
print("Duplicates now:", df.duplicated().sum())

Rows now: 1312
Duplicates now: 3

### **Look at the duplicated rows using loc**

In [26]:
# Coding 
df.loc[df.duplicated(), ["Name", "Age", "Fare"]]

                                                   Name   Age     Fare
1309                            Braund, Mr. Owen Harris  22.0   7.2500
1310  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
1311                             Heikkinen, Miss. Laina  26.0   7.9250

### **Removing Duplicates from the dataset**

In [27]:
# Coding
df = df.drop_duplicates()

print("Rows After:", len(df))
print("Duplicates After:", df.duplicated().sum())

Rows After: 1309
Duplicates After: 0

### **Step 5: Fix Data Types**

### To Check the Data Types of entire dataset

In [28]:
# Coding
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
dtype: object

In [29]:
# Coding 
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1309 entries, 0 to 1308
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     1309 non-null   int64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   object
 4   Sex          1309 non-null   object
 5   Age          1309 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Embarked     1309 non-null   object
dtypes: float64(2), int64(5), object(4)
memory usage: 122.7+ KB

### Survived and Pclass are categories in disguise; Sex and Embarked are true categories

In [30]:
# Coding 
df["Survived"] = df["Survived"].astype(int)
df["Sex"] = df["Sex"].astype("category")
df["Embarked"]= df["Embarked"].astype("category")
df.dtypes

PassengerId       int64
Survived          int32
Pclass            int64
Name             object
Sex            category
Age             float64
SibSp             int64
Parch             int64
Ticket           object
Fare            float64
Embarked       category
dtype: object

### **Step-6: Outlier**

In [31]:
# Coding 
df["Fare"].describe()

count    1308.000000
mean       33.295479
std        51.758668
min         0.000000
25%         7.895800
50%        14.454200
75%        31.275000
max       512.329200
Name: Fare, dtype: float64

### **See the extreme fares with loc**

In [32]:
# Coding
df.loc[df["Fare"]> 300, ["Name", "Pclass", "Fare"]]

                                                   Name  Pclass      Fare
258                                    Ward, Miss. Anna       1  512.3292
679                  Cardeza, Mr. Thomas Drake Martinez       1  512.3292
737                              Lesurer, Mr. Gustave J       1  512.3292
1234  Cardeza, Mrs. James Warburton Martinez (Charlo...       1  512.3292

### **IQR Rules**:

In [33]:
# Coding 
Q1 = df["Fare"].quantile(0.25)
Q3 = df["Fare"].quantile(0.75)
IQR = Q3- Q1
upper = Q3 + 1.5 * IQR

print("Q1:", Q1, "Q3:", Q3, "Upper Limit:", round(upper, 2))
print("Outlier:", (df["Fare"]> upper).sum())

Q1: 7.8958 Q3: 31.275 Upper Limit: 66.34
Outlier: 171

**Decision time.** The 512 fare was a real luxury ticket, not a mistake. Removing real data loses information.

A common middle path is **capping**: pull extreme values down to the upper limit instead of deleting rows.

### **Capping Fare at the upper limit using loc**

In [34]:
# Coding 
df.loc[df["Fare"]> upper, "Fare"].upper
df["Fare"].describe()

AttributeError: 'Series' object has no attribute 'upper'

### **Step 7: Clean Text and Categories**

The real **Sex** column is already clean, so let us **make it messy on purpose**, then clean it.

In [ ]:
# Coding
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1309 entries, 0 to 1308
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     1309 non-null   int32
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   object
 4   Sex          1309 non-null   category
 5   Age          1309 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Embarked     1309 non-null   category
dtypes: category(2), float64(2), int32(1), int64(4), object(2)
memory usage: 100.0+ KB

In [ ]:
# Coding 
print("Missing Values", df.isnull().sum())
print("Duplicates", df.duplicated().sum())
print("Shapes:", df.shape)

Missing Values PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           1
Embarked       0
dtype: int64
Duplicates 0
Shapes: (1309, 11)

### **Saving all the clean Dataset**

In [35]:
# Coding 
df.to_csv("titanic_clean.csv", index= False)
print("Saved titanic_clean.csv")

Saved titanic_clean.csv

## Practice Exercises

Use `loc` wherever possible.

1. Select the `Name`, `Age` and `Fare` of all passengers younger than 10.
2. How many third class passengers survived? (Filter with `loc`, then count.)
3. Rerun the Child/Adult labeling from Step 2. Why does every row get a label now?
4. Set the `Fare` of all passengers with `Fare` equal to 0 to the median fare (use `loc`).
5. Count missing values per column in the ORIGINAL dataset again and write one sentence for each column explaining your cleaning decision.
6. Challenge: create an `AgeGroup` column with values `Child` (below 13), `Teen` (13 to 19), `Adult` (20 to 59), `Senior` (60 plus), using only `loc`.