## **Pandas_Loc and Iloc Notebook**

### **Detail Comparision with Examples**:

In [39]:
# Coding 
import pandas as pd
df = pd.DataFrame({
    "Name": ["Mann", "James", "Jude", "lilly", "Lana", "Parker"], 
    "ID": [101, 102, 103, 104, 105, 106], 
    "Marks": [78, 80, 90, 67, 69, 70]
})
df

     Name   ID  Marks
0    Mann  101     78
1   James  102     80
2    Jude  103     90
3   lilly  104     67
4    Lana  105     69
5  Parker  106     70

### **loc** – Label-based Indexing

- **loc** is used to access data using **labels**
- Labels can be:
  - Index names /row label
  - Column names
- **Both start and end values are included**

In [40]:
# Coding 
df.set_index("ID", inplace = True)
df

       Name  Marks
ID
101    Mann     78
102   James     80
103    Jude     90
104   lilly     67
105    Lana     69
106  Parker     70

### **loc=access data using label index name value not index postion**

### Accessing value from rows and columns

In [41]:
# Coding
df.loc[103, ["Name", "Marks"]]

Name     Jude
Marks      90
Name: 103, dtype: object

### Accessing multiple rows value

In [42]:
# Coding 
df.loc[[101, 105, 106]]

       Name  Marks
ID
101    Mann     78
105    Lana     69
106  Parker     70

### Accessing values from specific rows

In [43]:
#Coding 
df.loc[103]

Name     Jude
Marks      90
Name: 103, dtype: object

### Accessing values using range

In [44]:
# Coding 
df.loc[102:105, ["Name", "Marks"]]

      Name  Marks
ID
102  James     80
103   Jude     90
104  lilly     67
105   Lana     69

## **iloc** – Integer Position-based Indexing

- **iloc** uses **integer positions**
- Index starts from **0**
- **End value is excluded**
- Similar to Python list slicing

In [45]:
# Coding
df.set_index("Marks")
df

       Name  Marks
ID
101    Mann     78
102   James     80
103    Jude     90
104   lilly     67
105    Lana     69
106  Parker     70

### Accessing multiple rows using iloc

In [47]:
# Coding
df.iloc[[0,2, 5]]

       Name  Marks
ID
101    Mann     78
103    Jude     90
106  Parker     70

### Accessing specific rows and column

In [50]:
# Coding
df.iloc[3,0]

'lilly'

### Accessing range of rows and column

In [54]:
# Coding
df.iloc[0:3, 0:2]

      Name  Marks
ID
101   Mann     78
102  James     80
103   Jude     90

## **Comparison Table**

| Feature | loc | iloc |
|------|-----|------|
| Type | Label-based | Integer position-based |
| Uses | Index & column names | Row & column numbers |
| Range | End included | End excluded |
| Similar to | Dictionary | Python list |
| Example | df.loc[101] | df.iloc[0] |

### Common Mistakes

❌ Using labels in **iloc**
```python
df.iloc[101]   # Error

**df.loc[0]   # KeyError**

## 📌 10. When to Use What? (Markdown Cell)

```markdown
### When to Use **loc**
- When index has meaningful labels (ID, Name, Date)
- When readability is important

### When to Use **iloc**
- When working with positions
- When index values are unknown
- For fast slicing like arrays