## **Pandas_Groupby Notebook**

### **What is GroupBy?**

A groupby() is used to split data into groups, apply a function, and combine results.

Split → Apply → Combine

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame({
    "Department": ['IT', 'HR', "IT", "Finance", "HR", "Finance", "IT"], 
    "Employee": ["A", 'B', 'C', 'D', 'E', 'F', 'G'], 
    'Salary': [50000, 40000, 55000, 60000, 42000, 65000, 58000],
    'Experience': [2, 1, 3, 5, 2, 6, 4]
})

df

  Department Employee  Salary  Experience
0         IT        A   50000           2
1         HR        B   40000           1
2         IT        C   55000           3
3    Finance        D   60000           5
4         HR        E   42000           2
5    Finance        F   65000           6
6         IT        G   58000           4

### **Simple Groupby**

In [4]:
# Coding
df.groupby('Department')

### Calculate mean salary per Department using groupby()

In [5]:
# Coding 
df.groupby('Department')["Salary"].mean()

Department
Finance    62500.000000
HR         41000.000000
IT         54333.333333
Name: Salary, dtype: float64

### The multiple aggregation using .groupby(); group **'Department'** and find aggregation of **'Salary'**

In [6]:
# Coding 
df.groupby("Department")["Salary"].agg(["mean", "max", "min", "sum"])

                    mean    max    min     sum
Department
Finance     62500.000000  65000  60000  125000
HR          41000.000000  42000  40000   82000
IT          54333.333333  58000  50000  163000

### Grouping multiple columns using .groupby(); Column **'Department** and **'Experience'** and find mean Salary

In [7]:
# Coding
df.groupby(["Department", "Experience"])["Salary"].mean()

Department  Experience
Finance     5             60000.0
            6             65000.0
HR          1             40000.0
            2             42000.0
IT          2             50000.0
            3             55000.0
            4             58000.0
Name: Salary, dtype: float64

### Count the numbers of employee in different department by using .groupby()

In [8]:
# Coding 
df.groupby("Department")["Employee"]. count()

Department
Finance    2
HR         2
IT         3
Name: Employee, dtype: int64

### Finding a **salary_range** using .groupby() also calculating max and min salary to find the range.

In [9]:
def salary_range(x):
    return x.max()- x.min()

df.groupby("Department")["Salary"].apply(salary_range)

Department
Finance    5000
HR         2000
IT         8000
Name: Salary, dtype: int64

## **Titanic Dataset Analysis**

In [10]:
import pandas as pd
df= pd.read_csv(r"C:\Users\HP\Downloads\titanic_dataset.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1306,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1307,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1308,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [11]:
# Coding 
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

### Q1. Find average Fare from each Passenger Class using .groupby()

In [12]:
# Coding 
df.groupby("Pclass")["Fare"].mean()

Pclass
1    87.508992
2    21.179196
3    13.302889
Name: Fare, dtype: float64

### Q2. Find the survival rate and death rate by Gender

In [13]:
# Coding 
df.groupby("Sex")["Survived"].mean()

Sex
female    0.82618
male      0.12930
Name: Survived, dtype: float64

In [14]:
df.groupby(["Survived", "Sex"]).count()

                 PassengerId  Pclass  Name  Age  SibSp  Parch  Ticket  Fare  \
Survived Sex
0        female           81      81    81   64     81     81      81    81
         male            734     734   734  565    734    734     734   733
1        female          385     385   385  324    385    385     385   385
         male            109     109   109   93    109    109     109   109

                 Cabin  Embarked
Survived Sex
0        female      6        81
         male      109       734
1        female    135       383
         male       45       109

### **Survival Rate by Gender**

**Female Survival Rate**

In [15]:
# Coding 
total_passenger = 1309
female_survived = 385
female_survival_rate = total_passenger/female_survived
print(female_survival_rate)

3.4

**Male Survival Rate**

In [16]:
# Coding 
total_passenger = 1309
male_survived = 109
male_survival_rate = total_passenger/male_survived
print(male_survival_rate)

12.009174311926605

### **Death Rate by Gender**

**Female Death Rate**

In [17]:
# Coding 
total_passenger = 1309
female_death = 81
female_death_rate = total_passenger/female_death
print(female_death_rate)

16.160493827160494

**Male Death Rate**

In [18]:
# Coding
total_passenger = 1309
male_death = 734
male_death_rate = total_passenger/male_death
print(male_death_rate)

1.7833787465940054

In [19]:
# Coding 
df.groupby("Sex")["Survived"].count()

Sex
female    466
male      843
Name: Survived, dtype: int64

### Q3. Use multiple aggregation on column **'Pclass'** and **'Fare'**

In [20]:
# Coding
df.groupby("Pclass")["Fare"].agg(["mean", "max", "min", "sum"])

             mean       max  min         sum
Pclass
1       87.508992  512.3292  0.0  28265.4043
2       21.179196   73.5000  0.0   5866.6374
3       13.302889   69.5500  0.0   9418.4452

### Q4. Group multiple columns using .groupby() and find the mean()

In [21]:
# Coding 
df.groupby(["Pclass", "Sex", "Survived"])["Fare"].mean()

Pclass  Sex     Survived
1       female  0           110.604167
                1           109.387028
        male    0            68.293593
                1            74.637320
2       female  0            18.250000
                1            23.533917
        male    0            19.773565
                1            21.095100
3       female  0            19.773093
                1            13.099828
        male    0            12.081262
                1            15.579696
Name: Fare, dtype: float64

### Q5. Find an average age of survival and non-survival passengers

In [22]:
# Coding
df.groupby("Survived")["Age"].mean()

Survived
0    30.510986
1    28.931079
Name: Age, dtype: float64

In [23]:
# Coding  
df.groupby("Survived")["Age"].count()

Survived
0    629
1    417
Name: Age, dtype: int64

### Q6. Count the number of male and female Passenger as per the class

In [24]:
# Coding 
df.groupby(["Sex", "Pclass"]).size()

Sex     Pclass
female  1         144
        2         106
        3         216
male    1         179
        2         171
        3         493
dtype: int64

### Q7. Find the average age of male and female passenger and create a new column as **'Average Age'**

In [25]:
# Coding 
#df["Average Age"]=df.groupby("Sex")["Age"].mean()
df.groupby("Sex")["Age"].mean()

Sex
female    28.687088
male      30.585228
Name: Age, dtype: float64

### **Questions from ChatGPT**

### Q8. Group the passengers by **Sex** and find the **average Age** for each gender.

In [26]:
# Coding 
df.groupby("Sex")["Age"].mean()

Sex
female    28.687088
male      30.585228
Name: Age, dtype: float64

### Q9. Group the passengers by **Pclass** and find the **average Fare** for each passenger class.

In [27]:
# Coding 
df.groupby("Pclass")["Fare"].mean()

Pclass
1    87.508992
2    21.179196
3    13.302889
Name: Fare, dtype: float64

### Q10. Group the passengers by **Sex** and count how many passengers are in each gender.

In [28]:
# Coding 
df.groupby("Sex")["PassengerId"].count()

Sex
female    466
male      843
Name: PassengerId, dtype: int64

### Q11. Group the passengers by **Pclass** and count the number of passengers in each class.

In [29]:
# Coding 
df.groupby("Pclass")["PassengerId"].count()

Pclass
1    323
2    277
3    709
Name: PassengerId, dtype: int64

### Q12. Group the passengers by **Embarked** and find the **average Fare** for each embarkation port.

In [30]:
# Coding 
df.groupby("Embarked")["Fare"].mean()

Embarked
C    62.336267
Q    12.409012
S    27.418824
Name: Fare, dtype: float64

### Q13. Group the passengers by **Survived** and find the **average Age** for survivors and non-survivors.

In [31]:
# Coding 
df.groupby("Survived")["Age"].mean()

Survived
0    30.510986
1    28.931079
Name: Age, dtype: float64

### Q14. Group the passengers by **Pclass** and find the maximum Fare paid in each class.

In [32]:
# Coding 
df.groupby("Pclass")["Fare"].max()

Pclass
1    512.3292
2     73.5000
3     69.5500
Name: Fare, dtype: float64

### Q15. Group the passengers by **Pclass** and find the minimum Age in each class.

In [33]:
# Coding 
df.groupby("Pclass")["Age"].min()

Pclass
1    0.92
2    0.67
3    0.17
Name: Age, dtype: float64

### Q16. Group the passengers by both **Sex** and **Pclass** and count the number of passengers in each group.

In [34]:
# Coding 
df.groupby(["Sex", "Pclass"])["PassengerId"].count()

Sex     Pclass
female  1         144
        2         106
        3         216
male    1         179
        2         171
        3         493
Name: PassengerId, dtype: int64

### Q17. Group by **Sex** and **Pclass** and find the average Fare for each combination.

In [35]:
# Coding 
df.groupby(["Sex", "Pclass"])["Fare"].mean()

Sex     Pclass
female  1         109.412385
        2          23.234827
        3          15.324250
male    1          69.888385
        2          19.904946
        3          12.415462
Name: Fare, dtype: float64

### Q18. Group by **Pclass** and **Survived** and count how many passengers are in each group.

In [36]:
# Coding 
df.groupby(["Pclass", "Survived"])["PassengerId"].count()

Pclass  Survived
1       0           137
        1           186
2       0           160
        1           117
3       0           518
        1           191
Name: PassengerId, dtype: int64

### Q19. Group by **Sex** and calculate the average Age, average Fare, and total Survived for each gender.

In [37]:
# Coding 
df.groupby("Sex")[["Age", "Fare"]].mean()

              Age       Fare
Sex
female  28.687088  46.198097
male    30.585228  26.154601

In [38]:
# Coding 
df.groupby("Sex")["Survived"].count()

Sex
female    466
male      843
Name: Survived, dtype: int64

### Q20. Group by **Pclass** and calculate the minimum, maximum, and average Fare for each class.

In [39]:
# Coding 
df.groupby("Pclass")["Fare"].agg(["max", "min", "mean"])

             max  min       mean
Pclass
1       512.3292  0.0  87.508992
2        73.5000  0.0  21.179196
3        69.5500  0.0  13.302889

### Q21. Group by **Embarked** and **Sex** and find the average Age for each combination.

In [40]:
# Coding 
df.groupby(["Embarked", "Sex"])["Age"].mean()

Embarked  Sex
C         female    31.224490
          male      33.284386
Q         female    25.458333
          male      31.557692
S         female    27.877235
          male      29.942394
Name: Age, dtype: float64

### Q22. Group by **Pclass** and calculate the total Fare paid by passengers in each class.

In [41]:
# Coding 
df.groupby("Pclass")["Fare"].sum()

Pclass
1    28265.4043
2     5866.6374
3     9418.4452
Name: Fare, dtype: float64

### Q23. Group by **Pclass** and calculate the total Fare paid by passengers in each class: Number of passengers, Average age, Average fare, Maximum fare

In [42]:
# Coding 
df.groupby("Pclass")[["Fare", "PassengerId", "Age"]].agg(["sum", "mean", "max"])

              Fare                      PassengerId                    \
               sum       mean       max         sum        mean   max
Pclass
1       28265.4043  87.508992  512.3292      217215  672.492260  1306
2        5866.6374  21.179196   73.5000      186024  671.566787  1298
3        9418.4452  13.302889   69.5500      454156  640.558533  1309

             Age
             sum       mean   max
Pclass
1       11121.42  39.159930  80.0
2        7701.25  29.506705  70.0
3       12433.00  24.816367  74.0

In [43]:
# Coding 
df.groupby("Pclass")["Fare"].agg(["sum", "mean", "max"])

               sum       mean       max
Pclass
1       28265.4043  87.508992  512.3292
2        5866.6374  21.179196   73.5000
3        9418.4452  13.302889   69.5500

In [44]:
# Coding 
df.groupby("Pclass")["Age"].mean()

Pclass
1    39.159930
2    29.506705
3    24.816367
Name: Age, dtype: float64

In [45]:
# Coding 
df.groupby("Pclass")["PassengerId"].count()

Pclass
1    323
2    277
3    709
Name: PassengerId, dtype: int64

### Q24. Group by **Pclass** and **Sex**, then calculate the average Age and average Fare for each group.

In [46]:
# Coding 
df.groupby(["Pclass", "Sex"])[["Age", "Fare"]].mean()

                     Age        Fare
Pclass Sex
1      female  37.037594  109.412385
       male    41.029272   69.888385
2      female  27.499223   23.234827
       male    30.815380   19.904946
3      female  22.185329   15.324250
       male    25.962264   12.415462

### Q25. Group by **Embarked** and calculate: Number of passengers, Average age, Average fare, Maximum fare

In [47]:
# Coding 
df.groupby("Embarked")[["Age", "Fare", "PassengerId"]].agg(["count", "mean", "max"])

           Age                   Fare                      PassengerId  \
         count       mean   max count       mean       max       count
Embarked
C          212  32.332170  71.0   270  62.336267  512.3292         270
Q           50  28.630000  70.5   123  12.409012   90.0000         123
S          782  29.245205  80.0   913  27.418824  263.0000         914


                mean   max
Embarked
C         690.655556  1309
Q         668.593496  1303
S         643.095186  1308

In [48]:
# Coding 
df.groupby("Embarked")["Fare"].agg(["mean", "max"])

               mean       max
Embarked
C         62.336267  512.3292
Q         12.409012   90.0000
S         27.418824  263.0000

In [49]:
# Coding 
df.groupby("Embarked")["Age"].mean()

Embarked
C    32.332170
Q    28.630000
S    29.245205
Name: Age, dtype: float64

In [50]:
# Coding 
df.groupby("Embarked")["PassengerId"].count()

Embarked
C    270
Q    123
S    914
Name: PassengerId, dtype: int64

### Q26. Group by **Pclass** and **Survived**, then calculate the average Age, average Fare, and number of passengers for each combination.

In [51]:
# Coding 
df.groupby(["Pclass", "Survived"]) [["Age", "Fare", "PassengerId"]].agg(["mean", "count"])

                       Age              Fare       PassengerId
                      mean count        mean count        mean count
Pclass Survived
1      0         42.302632   114   69.220102   137  694.379562   137
       1         37.052471   170  100.979840   186  656.370968   186
2      0         32.513423   149   19.716431   160  715.550000   160
       1         25.506696   112   23.179559   117  611.418803   117
3      0         26.022978   366   13.152465   517  635.310811   518
       1         21.545111   135   13.710057   191  654.790576   191

### Q27. Group by **Sex** and **Pclass** and find the group with the highest average Fare. Hint: use groupby(), .agg() or .mean(), and sorting.

In [63]:
# Coding 
df.groupby(["Sex", "Pclass"])["Fare"].agg("mean").sort_values()

Sex     Pclass
male    3          12.415462
female  3          15.324250
male    2          19.904946
female  2          23.234827
male    1          69.888385
female  1         109.412385
Name: Fare, dtype: float64